spring.application.name=demo-agent-app
server.port=8083

spring.cloud.nacos.discovery.namespace=xxx
spring.cloud.nacos.discovery.server-addr=xxx
spring.cloud.nacos.discovery.username=xxx
spring.cloud.nacos.discovery.password=xxx
